spring:
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password: 2023
      timeout: 50000
      lettuce:
        pool:
          max-active: 200
          max-wait: -1
          max-idle: 10
          min-idle: 0

  # 多数据源
  datasource:
    dynamic:
      primary: ms_a #设置默认的数据源或者数据源组,默认值即为master
      strict: true #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        ms_a:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 2023
          url: jdbc:mysql://127.0.0.1:3306/ms_a?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
          hikari:
            max-lifetime: 500000


# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false

  configuration:
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
